//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duologue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duologue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have defeated my minions,.
        /// </summary>
        internal static string Boss_Moloch1 {
            get {
                return ResourceManager.GetString("Boss_Moloch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but you will not defeat me!.
        /// </summary>
        internal static string Boss_Moloch2 {
            get {
                return ResourceManager.GetString("Boss_Moloch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerUI/game-over_en_US.
        /// </summary>
        internal static string Filename_GameOver {
            get {
                return ResourceManager.GetString("Filename_GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival Mode.
        /// </summary>
        internal static string GameScreen_SurvivalWave {
            get {
                return ResourceManager.GetString("GameScreen_SurvivalWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave {0}-{1}.
        /// </summary>
        internal static string GameScreen_Wave {
            get {
                return ResourceManager.GetString("GameScreen_Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2009 Funavision, Inc. All rights reserved..
        /// </summary>
        internal static string Intro_Copyright {
            get {
                return ResourceManager.GetString("Intro_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains game assets released under Creative Commons and Microsoft Permissive Licenses..
        /// </summary>
        internal static string Intro_Legal1 {
            get {
                return ResourceManager.GetString("Intro_Legal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by the Mimicware Engine. See game credits for more details..
        /// </summary>
        internal static string Intro_Legal2 {
            get {
                return ResourceManager.GetString("Intro_Legal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Intro_Loading {
            get {
                return ResourceManager.GetString("Intro_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medal Display Case.
        /// </summary>
        internal static string MainMenu_Achievements {
            get {
                return ResourceManager.GetString("MainMenu_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy the full game!.
        /// </summary>
        internal static string MainMenu_BuyMe {
            get {
                return ResourceManager.GetString("MainMenu_BuyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string MainMenu_Credits {
            get {
                return ResourceManager.GetString("MainMenu_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Arcade.
        /// </summary>
        internal static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string MainMenu_GameSelect_Back {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play campaign mode.
        /// </summary>
        internal static string MainMenu_GameSelect_Campaign {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play infinite mode.
        /// </summary>
        internal static string MainMenu_GameSelect_InfiniteMode {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_InfiniteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play survival mode.
        /// </summary>
        internal static string MainMenu_GameSelect_Survival {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the battle!.
        /// </summary>
        internal static string MainMenu_Play {
            get {
                return ResourceManager.GetString("MainMenu_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start.
        /// </summary>
        internal static string MainMenu_PressStart {
            get {
                return ResourceManager.GetString("MainMenu_PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to beat the campaign with the least lives lost!.
        /// </summary>
        internal static string MainMenu_ToolTip_InfiniteMode {
            get {
                return ResourceManager.GetString("MainMenu_ToolTip_InfiniteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survive against an endless enemy assault!.
        /// </summary>
        internal static string MainMenu_ToolTip_SurvivalMode {
            get {
                return ResourceManager.GetString("MainMenu_ToolTip_SurvivalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy the full game to play this mode!.
        /// </summary>
        internal static string MainMenu_ToolTip_TrialMode {
            get {
                return ResourceManager.GetString("MainMenu_ToolTip_TrialMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the campaign in co-op.
        /// </summary>
        internal static string Medal_Desc_BFF {
            get {
                return ResourceManager.GetString("Medal_Desc_BFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed 50% of the campaign.
        /// </summary>
        internal static string Medal_Desc_Experienced {
            get {
                return ResourceManager.GetString("Medal_Desc_Experienced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed every enemy type.
        /// </summary>
        internal static string Medal_Desc_Exterminator {
            get {
                return ResourceManager.GetString("Medal_Desc_Exterminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled the score back to all zeros.
        /// </summary>
        internal static string Medal_Desc_HeavyRoller {
            get {
                return ResourceManager.GetString("Medal_Desc_HeavyRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play 50% of campaign in 4 player co-op.
        /// </summary>
        internal static string Medal_Desc_KeyParty {
            get {
                return ResourceManager.GetString("Medal_Desc_KeyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 1000 enemies.
        /// </summary>
        internal static string Medal_Desc_Kilokillage {
            get {
                return ResourceManager.GetString("Medal_Desc_Kilokillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed wave 100 of Survival Mode.
        /// </summary>
        internal static string Medal_Desc_NoEndInSight {
            get {
                return ResourceManager.GetString("Medal_Desc_NoEndInSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed 39,516 enemies.
        /// </summary>
        internal static string Medal_Desc_Seriously {
            get {
                return ResourceManager.GetString("Medal_Desc_Seriously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed the campaign.
        /// </summary>
        internal static string Medal_Desc_TourOfDuty {
            get {
                return ResourceManager.GetString("Medal_Desc_TourOfDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed 25% of the campaign.
        /// </summary>
        internal static string Medal_Desc_WetFeet {
            get {
                return ResourceManager.GetString("Medal_Desc_WetFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFF.
        /// </summary>
        internal static string Medal_Name_BFF {
            get {
                return ResourceManager.GetString("Medal_Name_BFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced.
        /// </summary>
        internal static string Medal_Name_Experienced {
            get {
                return ResourceManager.GetString("Medal_Name_Experienced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterminator.
        /// </summary>
        internal static string Medal_Name_Exterminator {
            get {
                return ResourceManager.GetString("Medal_Name_Exterminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled the score.
        /// </summary>
        internal static string Medal_Name_HeavyRoller {
            get {
                return ResourceManager.GetString("Medal_Name_HeavyRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key party.
        /// </summary>
        internal static string Medal_Name_KeyParty {
            get {
                return ResourceManager.GetString("Medal_Name_KeyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilokillage.
        /// </summary>
        internal static string Medal_Name_Kilokillage {
            get {
                return ResourceManager.GetString("Medal_Name_Kilokillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end in sight.
        /// </summary>
        internal static string Medal_Name_NoEndInSight {
            get {
                return ResourceManager.GetString("Medal_Name_NoEndInSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seriously?.
        /// </summary>
        internal static string Medal_Name_Seriously {
            get {
                return ResourceManager.GetString("Medal_Name_Seriously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour of duty.
        /// </summary>
        internal static string Medal_Name_TourOfDuty {
            get {
                return ResourceManager.GetString("Medal_Name_TourOfDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet feet.
        /// </summary>
        internal static string Medal_Name_WetFeet {
            get {
                return ResourceManager.GetString("Medal_Name_WetFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not yet earned).
        /// </summary>
        internal static string MedalCase_Locked {
            get {
                return ResourceManager.GetString("MedalCase_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potato+1.
        /// </summary>
        internal static string MedalCase_Potato {
            get {
                return ResourceManager.GetString("MedalCase_Potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy types killed: {0}/{1}  Total enemies killed: {2}.
        /// </summary>
        internal static string MedalCase_Stats {
            get {
                return ResourceManager.GetString("MedalCase_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medal Display Case.
        /// </summary>
        internal static string MedalCase_Title {
            get {
                return ResourceManager.GetString("MedalCase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase the full game to earn medals!.
        /// </summary>
        internal static string MedalCase_TrialMode {
            get {
                return ResourceManager.GetString("MedalCase_TrialMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Main Menu.
        /// </summary>
        internal static string PauseScreen_ExitMainMenu {
            get {
                return ResourceManager.GetString("PauseScreen_ExitMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Paused.
        /// </summary>
        internal static string PauseScreen_GamePaused {
            get {
                return ResourceManager.GetString("PauseScreen_GamePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medal Display Case.
        /// </summary>
        internal static string PauseScreen_MedalCase {
            get {
                return ResourceManager.GetString("PauseScreen_MedalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume the battle.
        /// </summary>
        internal static string PauseScreen_ResumeGame {
            get {
                return ResourceManager.GetString("PauseScreen_ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave {0}-{1}.{2}.
        /// </summary>
        internal static string PauseScreen_WaveNum {
            get {
                return ResourceManager.GetString("PauseScreen_WaveNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect controller.
        /// </summary>
        internal static string PlayerSelect_ConnectController {
            get {
                return ResourceManager.GetString("PlayerSelect_ConnectController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;B&quot; to cancel.
        /// </summary>
        internal static string PlayerSelect_CountdownPressB {
            get {
                return ResourceManager.GetString("PlayerSelect_CountdownPressB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;A&quot; to join and &quot;Start&quot; to begin.
        /// </summary>
        internal static string PlayerSelect_MainText {
            get {
                return ResourceManager.GetString("PlayerSelect_MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;A&quot; to join.
        /// </summary>
        internal static string PlayerSelect_PressA {
            get {
                return ResourceManager.GetString("PlayerSelect_PressA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Start&quot; when ready.
        /// </summary>
        internal static string PlayerSelect_PressStart {
            get {
                return ResourceManager.GetString("PlayerSelect_PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Life!.
        /// </summary>
        internal static string ScoreUI_ExtraLife {
            get {
                return ResourceManager.GetString("ScoreUI_ExtraLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string ScoreUI_GameOver {
            get {
                return ResourceManager.GetString("ScoreUI_GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths:.
        /// </summary>
        internal static string ScoreUI_InfiniteMode_Lives {
            get {
                return ResourceManager.GetString("ScoreUI_InfiniteMode_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives:.
        /// </summary>
        internal static string ScoreUI_Lives {
            get {
                return ResourceManager.GetString("ScoreUI_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: To kill Spawners, shoot them as they beam in reinforcements..
        /// </summary>
        internal static string Tip001 {
            get {
                return ResourceManager.GetString("Tip001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Some enemies can change their color. Be sure to watch for it..
        /// </summary>
        internal static string Tip002 {
            get {
                return ResourceManager.GetString("Tip002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: If an enemy does not have eyes, light will have no effect on them..
        /// </summary>
        internal static string Tip003 {
            get {
                return ResourceManager.GetString("Tip003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Off screen enemies have arrows that point to them..
        /// </summary>
        internal static string Tip004 {
            get {
                return ResourceManager.GetString("Tip004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Shooting enemies to the rhythm boosts your score..
        /// </summary>
        internal static string Tip005 {
            get {
                return ResourceManager.GetString("Tip005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: The intensity of the background music reflects your performance..
        /// </summary>
        internal static string Tip006 {
            get {
                return ResourceManager.GetString("Tip006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Enemies that are grey are immune to attack..
        /// </summary>
        internal static string Tip007 {
            get {
                return ResourceManager.GetString("Tip007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Don&apos;t stand between two Unclean Rots..
        /// </summary>
        internal static string Tip008 {
            get {
                return ResourceManager.GetString("Tip008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Sometimes it is best to not kill the leader first..
        /// </summary>
        internal static string Tip009 {
            get {
                return ResourceManager.GetString("Tip009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Remember to use your light to keep enemies at bay..
        /// </summary>
        internal static string Tip010 {
            get {
                return ResourceManager.GetString("Tip010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Left Stick to move and the Right Stick to fire..
        /// </summary>
        internal static string Tutorial_1 {
            get {
                return ResourceManager.GetString("Tutorial_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Left and Right Triggers to swap cannon and light colors..
        /// </summary>
        internal static string Tutorial_2 {
            get {
                return ResourceManager.GetString("Tutorial_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the light to ward off opposite colored enemies..
        /// </summary>
        internal static string Tutorial_3 {
            get {
                return ResourceManager.GetString("Tutorial_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the game with the least amount of deaths!.
        /// </summary>
        internal static string Tutorial_InfiniteMode {
            get {
                return ResourceManager.GetString("Tutorial_InfiniteMode", resourceCulture);
            }
        }
    }
}
