//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duologue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duologue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled the score back to all zeros.
        /// </summary>
        internal static string Achievement_Desc_RolledScore {
            get {
                return ResourceManager.GetString("Achievement_Desc_RolledScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled the score.
        /// </summary>
        internal static string Achievement_Name_RolledScore {
            get {
                return ResourceManager.GetString("Achievement_Name_RolledScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Achievement_Points_RolledScore {
            get {
                return ResourceManager.GetString("Achievement_Points_RolledScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string MainMenu_Achievements {
            get {
                return ResourceManager.GetString("MainMenu_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string MainMenu_Credits {
            get {
                return ResourceManager.GetString("MainMenu_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Arcade.
        /// </summary>
        internal static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string MainMenu_GameSelect_Back {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the campaign.
        /// </summary>
        internal static string MainMenu_GameSelect_Campaign {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play infinite mode.
        /// </summary>
        internal static string MainMenu_GameSelect_Infinite {
            get {
                return ResourceManager.GetString("MainMenu_GameSelect_Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards.
        /// </summary>
        internal static string MainMenu_Leaderboards {
            get {
                return ResourceManager.GetString("MainMenu_Leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string MainMenu_MultiPlayer {
            get {
                return ResourceManager.GetString("MainMenu_MultiPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string MainMenu_SinglePlayer {
            get {
                return ResourceManager.GetString("MainMenu_SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives: {0}.
        /// </summary>
        internal static string ScoreUI_Lives {
            get {
                return ResourceManager.GetString("ScoreUI_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}.
        /// </summary>
        internal static string ScoreUI_Player {
            get {
                return ResourceManager.GetString("ScoreUI_Player", resourceCulture);
            }
        }
    }
}
